/**
 * Which settings each field type may actually be given.
 *
 * Kept here rather than as conditions scattered through the panel so the rules
 * can be read in one place, and checked against what the serializer will really
 * do with them. A toggle the serializer ignores is worse than no toggle: it
 * looks like it did something.
 *
 * Free of imports so it can be tested without building the app.
 */

/**
 * Types where "required" cannot mean anything.
 *
 *  - `submit` is a button, not an answer.
 *  - `submission_id` is generated by the server; the visitor never touches it.
 *  - `hidden` is never shown, so there is nobody to require it of.
 *  - `range` always holds a value — the slider is always somewhere — so the
 *    check could never once fail.
 *  - `count` reads out another field's length; it is not an answer of its own.
 *
 * The serializer drops the star on the first three anyway; range would carry it
 * and still never fire.
 */
export const NEVER_REQUIRED = [ 'submit', 'submission_id', 'hidden', 'range', 'count' ];

/**
 * Types Contact Form 7 always requires whatever we ask.
 *
 * There is no `[radio*]` tag: CF7 applies a required rule to every radio group.
 * Nor is there a `[quiz*]` — an unanswered quiz fails the quiz validation filter
 * on its own, so a star would say nothing the tag does not already say.
 *
 * The toggle stays on screen, on and disabled, because "why can I not turn this
 * off" is a better question for a user to have than a silently ignored switch.
 */
export const ALWAYS_REQUIRED = [ 'radio', 'quiz' ];

export const showsRequired = ( type ) => ! NEVER_REQUIRED.includes( type );

export const requiredLocked = ( type ) => ALWAYS_REQUIRED.includes( type );

/**
 * What the toggle reads, given the stored value.
 *
 * @param {string}  type   Field type.
 * @param {boolean} stored Whether the field was saved as required.
 * @return {boolean} Whether the toggle shows as on.
 */
export const isRequired = ( type, stored ) => ( requiredLocked( type ) ? true : !! stored );

/**
 * Types that can start with one of their choices already picked.
 *
 * Contact Form 7 does this natively with `default:N`, a 1-based index into the
 * choice list, so nothing has to be smuggled through a marker class — the
 * generic option handling already carries it both ways.
 *
 * `country` is absent on purpose: it is our own tag and picks its starting value
 * through Pre-fill instead.
 */
export const HAS_DEFAULT_CHOICE = [ 'select', 'radio', 'checkbox' ];

export const hasDefaultChoice = ( type ) => HAS_DEFAULT_CHOICE.includes( type );

/**
 * The choice currently marked as the default, as a 1-based index.
 *
 * Returns 0 for "none", which is also what an index left pointing past the end
 * of a shortened choice list becomes — CF7 ignores those, and showing the
 * picker as empty says the same thing rather than naming a choice that is gone.
 *
 * @param {string|number} stored  The saved `default:N` index.
 * @param {string[]}      choices The field's current choices.
 * @return {number} A 1-based index, or 0 for none.
 */
export const defaultChoice = ( stored, choices ) => {
	const index = parseInt( stored, 10 );
	const count = ( choices || [] ).length;

	return index > 0 && index <= count ? index : 0;
};
